language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build
